version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

[transient_prompt]
  template = '➜ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

  [[blocks.segments]]
    template = '@{{ .UserName }} '
    foreground = '#62ED8B'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '➜'
    foreground = '#62ED8B'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = '#56B6C2'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = ' <#DDB15F>git(</>{{ .HEAD }}<#DDB15F>)</>'
    foreground = '#D4AAFC'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    template = ' '
    foreground = '#DCB977'
    type = 'status'
    style = 'plain'
